---
apiVersion: v1
kind: Service

metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: skyblock
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

spec:
  publishNotReadyAddresses: true

  selector:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: skyblock

  ports:
    - name: server
      port: 25565
    - name: rcon
      port: 25575
    - name: mapper
      port: 8123

...
